### ISSUE TITLE
Monitoring tab in CUI returns error 500

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#23]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit)**
1. login as a regular user;
2. Click on the "monitoring tab" top right of user interface.
### Expected behaviour

The monitoring tab is shown.
### Actual behaviour

500 internal server error

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
