### ISSUE TITLE
details on actors in single bulletins or incidents appear as incomplete

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#24]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to the incidents -- https://demo2.corroborator.org/corroborator/#tab/incident -- or to the bulletins -- https://demo2.corroborator.org/corroborator/#tab/bulletin -- section in CUI
2. Select and expand an incident or a bulletin. In this particular case it will be clearer if you click one with related actors, as https://demo2.corroborator.org/corroborator/#incident/4
3. In the box on the right-hand side of the screen, details on bulletin or incident appear.
### Expected results

Clear details on each actors should be visible.
### Actual results

Boxes on actors contain partial info: "Lives in Albacete works as a (en)".

![bulletin_actor_details](https://cloud.githubusercontent.com/assets/9517238/13847093/a64d8d14-ec4b-11e5-95e8-57ee5f07d318.png)

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3 (though could probably do with some re-design)
