### ISSUE TITLE
character encoding is inconsistent

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#25]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to admin panel, and click on "Sources" to open https://demo2.corroborator.org/admin/corroborator_app/source/
2. Click on "Add source" in the top right corner
3. Add a source name containing " ' " character  -- as in "L'Espresso" (or also cyrillic characters) in "Name en:" box.
4. Save.
5. Go to user panel (log out and log in again to see changes in admin panel).
6. Go to Bulletins section and create a new bulletin.
7. Click on the "Sources" drop-down menu 
### Expected results

The special character should be visible.
### Actual results

Instead of the " ' " character the output is: &#39;
### Notes

Special characters encoding works if data is entered from user panel. 
This doesn't apply to all special characters -- see source Süddeutsche Zeitung.

![apostrophe](https://cloud.githubusercontent.com/assets/9517238/13847354/20717adc-ec4d-11e5-8037-a62d0bd02a88.png)

**Comment by graphiclunarkid** [comment]
This won't occur very often in Ukrainian or Russian as they don't often use characters that end up as HTML escape codes!

**Comment by ggaughan** [comment]
Ukrainian place names seem to have lots of 's - so I'll fix this at the same time as fixing the location drop down to show them.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
