### ISSUE TITLE
Character encoding in admin panel

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#26]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to admin panel, and click on "Sources" to open https://demo2.corroborator.org/admin/corroborator_app/source/
2. Click on "Add source" in the top right corner
3. Add a source name containing cyrillic characters in "Name en:" box or containing arabic characters in "Name ar:" box (as in picture below).

![add_source_arabic1](https://cloud.githubusercontent.com/assets/9517238/13847890/bc737ca8-ec4f-11e5-948f-fb249c3c8ba2.png)
1. Save.
2. Go back to https://demo2.corroborator.org/admin/corroborator_app/source/
3. Select source created with arabic title.
### Expected results

Cyrillic and arabic characters should be visible, all the more because Corroborator is localized in Russian and Arabic.
### Actual results

Arabic and Cyrillic characters turn into question marks.

![add_source_arabic_saved](https://cloud.githubusercontent.com/assets/9517238/13847906/d5f53252-ec4f-11e5-91d8-04d7e0bf4dad.png)

![add_source_charencoding](https://cloud.githubusercontent.com/assets/9517238/13847920/df8d54de-ec4f-11e5-9478-2e37b248b667.png)

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
