### ISSUE TITLE
New user cannot edit items and has an incomplete CUI

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#31]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. In admin panel, go to https://demo2.corroborator.org/admin/auth/user/
2. Click on "Add user" in top right corner.
3. Fill in the data and click on "Save".
4. Log in as new user.

In alternative, the same issue can be seen also by logging in as admin in CUI.
### Expected results

New user should have the same privileges and see the same interface as demo user.
### Actual results

The user cannot edit items despite the fact that they're assigned to this new user.
When logged as new user, the CUI does not show upper menu with "Main", "Reporting", "Administration" and "Monitoring".

new user screenshot:

![new_user_cui](https://cloud.githubusercontent.com/assets/9517238/13849718/9daba766-ec57-11e5-8af3-b1e7184c7487.PNG)

admin screenshot:

![admin_cui](https://cloud.githubusercontent.com/assets/9517238/13874184/6f9b6d3a-ecf6-11e5-9fb8-1f855a0274a6.png)

**Comment by ggaughan** [comment]
Adding a new user doesn't give them any specific permissions, other than the ability to log in. The demo user has been added to all the 'analyst' groups and has been given the following extra permissions (needed for Edit):
        'Can assign users via api',
        'Can delete entities via api',
        'Can edit entities via api',
        'Can edit assigned entities via api',
These need to be added via the User admin.
