### ISSUE TITLE
Search for selecting media in Bulletins or Actors shows unrecognizable items

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#33]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Create New Bulletin or new Actor (or edit an existing one) in CUI.
2. In "Related media" in Bulletin edit interface, or in "Actor image" in Actor edit interface, click on "Search".
3. A box with all uploaded media will appear.
### Expected results

Uploaded media should be easy to identify in the list, thanks to thumbnails and/or names.
### Actual results

Media in the list can only be identified by the upload date or file type (picture vs. video).

![actors_edit_thumbnails](https://cloud.githubusercontent.com/assets/9517238/13850753/9cbdbb92-ec5b-11e5-8d15-cecea40ef40a.png)

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3

**Comment by florianap** [comment]
thumbnails are now visible for images, but videos are still not identifiable. There's an alt text that pops up for some of the assets when hovering over them with the mouse, but this behaviour is not consistent. It would be better to have a visible title for each asset.

**Comment by ggaughan** [comment]
Video thumbnails were turned off. I've re-enabled them & deployed to demo2 and demo3 (although I found another issue along the way #52).

The popup text only appears if the media was given a caption during the upload. Changing it so any title is always visible should be a separate enhancement issue, I think.
