### ISSUE TITLE
image pop-ups have fixed width

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#35]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to https://demo2.corroborator.org/corroborator/#tab/bulletin
2. Select and expand "Wood 1" bulletin: https://demo2.corroborator.org/corroborator/#bulletin/3/expanded
3. Double-click one of the attached image thumbnails.
### Expected results

A pop-up showing the entire image should appear.
### Actual results

The pop-up that appears by double-clicking a thumbnail has a fixed width that doesn't match with the image size. The height of the pop-up is fitting instead.

![image_box](https://cloud.githubusercontent.com/assets/9517238/13853158/c203685c-ec65-11e5-9300-4c5029a5c277.png)

**Comment by ggaughan** [comment]
deployed to demo2 and demo3
