### ISSUE TITLE
Actor conditions in admin panel have all the same identifier

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#37]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to Admin panel - Actor condition list: https://demo2.corroborator.org/admin/corroborator_app/actorcondition/
### Expected results

Each condition should have a different identifier.
### Actual results

Actor conditions all appear in the list with the name "ActorCondition object" and the admin must select them one by one in order to identify them.

![actorcondition_list](https://cloud.githubusercontent.com/assets/9517238/13853512/52141558-ec67-11e5-9254-c670d08363db.png)

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
