### ISSUE TITLE
Items in bulletin list in admin interface are labeled by identical or unclear identifiers

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#38]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to Admin panel - Bulletins https://demo2.corroborator.org/admin/corroborator_app/bulletin/
2. Click on Add bulletin in the top right corner.
3. Scroll down to "Bulletin comments:", "Bulletin imported comments:", "Times:", "Actors role:", and "Medias:".
### Expected results

The items in these menus should be clearly identifiable by different and clear names.
### Actual results
- All items have the same name "Comment object" in the Bulletin comments:" and "Bulletin imported comments:" menus.
- All items have the same name "Media object" in the "Medias" menu.
- Items have unclear identifiers in "Times" and "Actors role" menus.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
