### ISSUE TITLE
automatic plurals in admin interface command lists?

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#39]
In https://demo2.corroborator.org/admin/corroborator_app/ there are several misspelled words.
Since all these typos are connected to irregular plural formation (e.g. "categorys"), I have the feeling that this list is created automatically starting from words in the singular form. If that's so, it should be fixed so as to have the correct spelling.
If this issue is not connected to an automatic plural formation, I will take care of it myself.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
