### ISSUE TITLE
Error 500 after saving new source without filling in reliability score

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#40]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps

Time of incidents: 17/03/2016 14.34 (CET); 17/03/2016 14.36 (CET); 17/03/2016 14.38(CET); 17/03/2016 18.02 (CET)
1. Go to Admin Panel - Sources https://demo2.corroborator.org/admin/corroborator_app/source/
2. Click on "Add source" in top right corner.
3. Fill in details on name of source and source type, add a comment but leave "Reliability score" blank.
4. Save.
### Expected results

Since nothing in the interface tells users that adding a reliability score is compulsory, after saving the item should be added to other sources.
### Actual results

Error 500.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
