### ISSUE TITLE
Blank page after adding source type in admin panel

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#41]
*\* tested with Iceweasel 38.7.0 on Debian 8 and Firefox 45.0 on Fedora 23**
### Reproduction steps

This isn't easy to reproduce. 
Time of incidents: 16/03/2016 14.59 (CET) and 16/03/2016 15.37 (CET).
In the second case the Noscript extension (version 2.9.0.4 on Firefox 45.0) was installed in the browser.
1. Go to Admin panel - Source type -- https://demo2.corroborator.org/admin/corroborator_app/sourcetype/
2. Click on "Add source" in top right corner.
3. Fill in details and save.
### Expected results

Item is saved and source type list is shown again.
### Actual results

A blank page (URL: https://demo2.corroborator.org/admin/corroborator_app/sourcetype/add/?_to_field=id&_popup=1 ) opened after saving the source type, but the item had been saved nevertheless.

This does not happen always, but I managed to reproduce it by activating Noscript for corroborator.org. I'm not really sure it iss connected to Noscript though, because the first time I saw it happen, the browser profile I was using didn't have any add-ons installed.

**Comment by ggaughan** [comment]
I can't replicate this. Could you try clearing your browser cache? The previous version of Django did things a different way and I wonder if you've some old admin js around.

**Comment by ggaughan** [comment]
No - hang on - looks like some Django files were included and I should update them

**Comment by ggaughan** [comment]
6ed287b66cbca0be8559bc5b90bc5609fa2dbe3b should help

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
