### ISSUE TITLE
Creating role type in admin panel returns blank page

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#45]
*\* tested with Iceweasel 38.7.0 on Debian 8 and Firefox 45.0 on Fedora 23**
### Reproduction steps
1. Go to admin panel -> Actor roles https://demo2.corroborator.org/admin/corroborator_app/actorrole/
2. Click on "Add actor role" in the top right corner.
3. Click on the "+" icon next to the "Role" drop-down menu.
4. Fill in details in "Name en:" and "Description en:"
5. Click save
### Expected results

The new role type should be created and the "Add actor role" page should appear.
### Actual results

The new role type is created, but a blank page appears.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
