### ISSUE TITLE
Arabic name required when creating actor condition in admin panel

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#50]
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Go to admin panel -> Actor conditions https://demo2.corroborator.org/admin/corroborator_app/actorcondition/
2. Click on "Add actor condition" in the top right corner.
3. Fill in "Name en: and "Description en:"
4. Click "Save"
### Expected results

As with other items, English name and description should be enough.
### Actual results

Arabic name is required and the interface gives back an error, without saving the item.
### Notes

Forcing the user to add an Arabic name in the form for creating an actor condition in the admin panel is a bit strange: not all Corroborator users will know Arabic and one is forced to write in English instead of Arabic in the "Name ar:" box.

![add_actorcondition](https://cloud.githubusercontent.com/assets/9517238/13881786/aceac4fc-ed22-11e5-9726-d69d9e335acb.png)

**Comment by graphiclunarkid** [comment]
Issue #51 is related. Possibly issue #6 too.

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3
