### ISSUE TITLE
Eliminate option for adding entries in Arabic in standard CUI: interface should be language-specific

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#51]
### Reproduction steps
1. Click on a single incident, bulletin or actor in the CUI.
2. Click "Edit" in the box on the right-hand side of the window.
3. Hover over box for Title (the same issue also applies to the following boxes in Bulletins and Incidents: Description; Events - Description; Events - Comment -- as well as for the following in Actors: Name; Description; Nickname; Occupation; Position/Rank; Ethnicity; Nationality; Religion; Spoken dialects).
4. When hovering with the mouse over the box, a language selection menu EN/AR will appear. Click on "AR": a new box will appear for Arabic.
### Expected results

Ideally, the language selection should be available only for particular customers who need it.
After clicking, there shouldn't be 2 boxes, but just one, for the selected language.
The primary interface should be language-specific.
### Actual results

A second window for Arabic appears, and it cannot be closed. It disappears only by saving the item.

![ar_edit](https://cloud.githubusercontent.com/assets/9517238/13924285/07955c24-ef84-11e5-99cf-52a4baec3a79.png)

![ar_edit2](https://cloud.githubusercontent.com/assets/9517238/13924294/0eb95474-ef84-11e5-8dbc-2d8db37991aa.png)

**Comment by ggaughan** [comment]
Deployed to demo2 and demo3 (will need a cache reset to load the latest JS - e.g. ctrl+f5)
