### ISSUE TITLE
Support user groups with mutually exclusive data-access rights

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator#56]
We want to support two different groups who can't see or modify each other's data.

This may exist already, in which case we just need to document how to configure the system correctly.

There are no groups at present - but perhaps we could set up two different classes of user.

**Comment by ggaughan** [comment]
Limited visibility doesn't seem to be possible. Limited editing per-user is possible via the assigned-user fields. Separate instances might be the simplest way to have separate groups (keeping search, media, etc. separate).

I've added my notes about the current permissions here: https://github.com/equalitie/open-corroborator/blob/updatedemo/doc/system.rst#permissions
