### ISSUE TITLE
Export all data to CSV

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator#57]
As an administrator I want to export the database as a CSV file so that I can use my data elsewhere.

Questions:
- Security of export files?
- Would a MySQL dump be better for our client's purposes?
- Do we include media or link to it instead?

**Comment by ggaughan** [comment]
Added 'Export to CSV' option to some of the main models via Admin actions.
Deployed to demo2 and demo3

**Comment by florianap** [comment]
it's not clear to me where this option can be found.

**Comment by ggaughan** [comment]
Sorry - admin actions are here:

![export_admin](https://cloud.githubusercontent.com/assets/212570/14979946/85f94430-111d-11e6-922a-52ea9d9bf093.png)

You need to select the items first. If there are multiple pages, you also need to choose "Select all ..."
