### ISSUE TITLE
Mobile-friendly form to add a bulletin

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator#58]
We could possibly create a single new mobile-friendly form for creating a bulletin via mobile. A link to this at the top of the homepage would allow users to find it easily on mobile.

We need a mock-up of the new form before we can work on this.

**Comment by ggaughan** [comment]
The 'demodata' sample user has a simplified bulletin/actor data entry form.

**Comment by ggaughan** [comment]
demodata user is deployed to demo2 and demo3 (password 'demo')
