### ISSUE TITLE
Populate locations with relevant data

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator#62]
If the customer can give us a list of (name,lat,lon) of locations to
import we can do this as a one-off.

@kromcuich will ask the customer for a list of locations.

**Comment by ggaughan** [comment]
I'll look at loading a list of Ukranian cities from somewhere (will help with #5 too)

**Comment by ggaughan** [comment]
List added as a fixture to app and deployment routines.

Deployed to demo2

**Comment by ggaughan** [comment]
Deployed to demo3
